name: kc-plates
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.4
  - torchvision>=0.19
  - pip:
      - ultralytics
      - albumentations
      - hydra-core
      - fastapi
      - matplotlib
      - opencv-python
      - omegaconf
      - "numpy<2"
      - gdown
      - easyocr
      - pandas
      - datasets
      - transformers