name: kc-plates
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.2
  - torchvision=0.17
  - pip:
      - ultralytics
      - albumentations
      - hydra-core
      - fastapi
      - matplotlib
      - opencv-python
      - omegaconf
      - "numpy<2"