languages: ['ch_sim', 'en']
gpu: false
preprocessing: true

images_path: data/raw/data_jpg/images/
annotations_path: data/predictions/detection/predictions_v4.txt
output_path: data/predictions/ocr/predictions_trocr_v7.txt

recognizer: trocr  # easyocr | trocr

trocr_model_path: "checkpoints/trocr/final"
device: "cuda"